services:
  backend:
    build: ./backend
    ports:
      - 2020:8080
    env_file:
      - .env-db
      - .env-sftp
    volumes:
      # pour se connecter à ssh sans mot de passe
      # pour générer la clé : ssh-keygen -t ed25519 -f sftp/keys/id_ed25519
      - ./sftp/keys/id_ed25519:/keys/id_ed25519

      - ./front/static:/usr/share/nginx/html:ro
    networks:
      - db-network
      - sftp-network
      - front-network
    depends_on:
      - db
      - sftp

  db:
    image: postgres:18-alpine
    env_file:
      - .env-db
    networks:
      - db-network
    volumes:
      - ./sql/postgres_data:/var/lib/postgresql
      - ./sql/init:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  sftp:
    image: lscr.io/linuxserver/openssh-server
    env_file:
      - .env-sftp
    networks:
      - sftp-network
    volumes:
      - ./sftp/data/:/home/nobody
      # la clé publique de la clé ssh générée au dessus
      - ./sftp/keys/id_ed25519.pub:/keys/id_ed25519.pub
    restart: unless-stopped
    ports:
      - 2222:2222

  front:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - front-network
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/static:/usr/share/nginx/html:ro
    depends_on:
      - backend

networks: 
  db-network:
    driver: bridge
  sftp-network:
    driver: bridge
  front-network:
    driver: bridge
