services:
  backend:
    build: ./backend
    ports:
      - 2020:8080
    env_file:
      - .env
    networks:
      - db-network
      - front-network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    networks:
      - db-network
    volumes:
      - ./sql/postgres_data:/var/lib/postgresql
      - ./sql/init:/docker-entrypoint-initdb.d/
    restart: unless-stopped
  front:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - front-network
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/static:/usr/share/nginx/html:ro
    depends_on:
      - backend

networks: 
  db-network:
    driver: bridge

  front-network:
    driver: bridge